### ISSUE TITLE
Unable to build for Android with versions 1.2.0-alpha01-devXX

### ISSUE THREAD

**Issue by tunjid** [JetBrains/compose-jb#1801]
I'm currently unable to built for Android using any of the dev builds for `1.2.0-alpha01-devXX`, although building for desktop works great.

The issue seems to be in the resolution of some android dependencies with a `-debug` suffix:

```
FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:mergeDebugResources'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:mergeDebugAssets'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:processDebugMainManifest'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':common:generateDebugRFile'.
> Could not resolve all files for configuration ':common:debugCompileClasspath'.
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Required by:
         project :common > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Required by:
         project :common > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Required by:
         project :common > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Required by:
         project :common > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Required by:
         project :common > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':android:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':android:debugRuntimeClasspath'.
   > Could not find org.jetbrains.compose.foundation:foundation-layout-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/foundation/foundation-layout-android-debug/1.2.0-alpha01-dev606/foundation-layout-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.foundation:foundation-layout:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.material:material-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/material/material-android-debug/1.2.0-alpha01-dev606/material-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.material:material:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.animation:animation-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/animation/animation-android-debug/1.2.0-alpha01-dev606/animation-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.animation:animation:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.runtime:runtime-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/runtime/runtime-android-debug/1.2.0-alpha01-dev606/runtime-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.runtime:runtime:1.2.0-alpha01-dev606
   > Could not find org.jetbrains.compose.ui:ui-util-android-debug:1.2.0-alpha01-dev606.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://repo.maven.apache.org/maven2/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
       - https://maven.pkg.jetbrains.space/public/p/compose/dev/org/jetbrains/compose/ui/ui-util-android-debug/1.2.0-alpha01-dev606/ui-util-android-debug-1.2.0-alpha01-dev606.pom
     Required by:
         project :android > org.jetbrains.compose.ui:ui-util:1.2.0-alpha01-dev606

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/7.0.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5s
46 actionable tasks: 41 executed, 5 up-to-date


```

**Comment by akurasov** [comment]
Should be fixed in the next 1.2 dev build

**Comment by tunjid** [comment]
@akurasov it appears there's a small publication bug still. If you look at the `pom.xml` of foundation 1.2.0-alpha01-dev620, it pulls in the wrong foundation version:

```
<dependency>
<groupId>androidx.compose.foundation</groupId>
<artifactId>foundation</artifactId>
<version>1.1.0</version>
<scope>runtime</scope>
</dependency>
```

Link to full pom [here](https://repo1.maven.org/maven2/org/jetbrains/compose/foundation/foundation/1.2.0-alpha01-dev620/foundation-1.2.0-alpha01-dev620.pom)

**Comment by akurasov** [comment]
@tunjid what is wrong with it? Currently 1.2.0-dev builds reference 1.1.0 version of Jetpack Compose.

**Comment by tunjid** [comment]
@akurasov oh I see, I thought dev builds used tip of the tree compose versions. For example on desktop I can use some lazy grid apis from the compose 1.2.0-alpha01 just fine. 

Thanks for fixing the original issue

**Comment by akurasov** [comment]
Nope, we set this version manually. Actually, you can override it, by just adding JC of required version to the dependencies explicitly. However, keep in mind that it affects only android binaries.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1801">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
