### ISSUE TITLE
IDEA: Annotations in project for Kotlin + Compose

### ISSUE THREAD

**Issue by nightrider77** [JetBrains/compose-jb#498]
I am working in IntelliJ IDEA.
I noticed that there are no annotations for almost all Compose UI components.
For example, no annotations for Column, Button, AlertDialog and so on.
But, for example, Text() has annotation.
What should I do to get annotations for **all things** that I use?

Maybe anyone has IDEA template for Kotlin + Compose, that will have all help references for beginners?

![image](https://user-images.githubusercontent.com/20248492/111080431-7d697900-850f-11eb-9e79-36d66465b99f.png)

![image](https://user-images.githubusercontent.com/20248492/111080463-a8ec6380-850f-11eb-8dde-7faf3cc860ac.png)

Thank you.

**Comment by Exidel** [comment]
Crtl+Click on function will show what parametrs it has and some devs descriptions. Questions like this better leave in discussion thread.

**Comment by nightrider77** [comment]
> Crtl+Click on function will show what parametrs it has and some devs descriptions. Questions like this better leave in discussion thread.

Yes, I use Ctrl+Click. But interesting why there are no instant annotations, like Text() has...
Recently I made project in Java, had no problems like that.

**Comment by Exidel** [comment]
It's early alpha and look like devs work now on exceptions only. Will wait for atleast beta version and normal documentation. Because annotations not that big problem as inability to share a state variables between @Composable functions. Ofc if you use compose for desktop...

**Comment by nightrider77** [comment]
> It's early alpha and look like devs work now on exceptions only. Will wait for atleast beta version and normal documentation. Because annotations not that big problem as inability to share a state variables between @composable functions. Ofc if you use compose for desktop...

I see...

![image](https://user-images.githubusercontent.com/20248492/111082490-a858ca80-8519-11eb-8dd5-e3c8fde22f0c.png)

**Comment by igordmn** [comment]
It is possible that it is a duplicate of https://github.com/JetBrains/compose-jb/issues/326

**Comment by ivakub** [comment]
```kt
import androidx.compose.desktop.Window
import androidx.compose.material.Text
fun main() = Window {
    Text("hi")
    AlertDialog()
}
@Composable
fun AlertDialog(
    title: (@Composable () -> Unit)? = null
) {}
@Target(
    AnnotationTarget.FUNCTION,
    AnnotationTarget.TYPE
)
annotation class Composable
```

**Comment by nightrider77** [comment]
@ivakub 
Can you please include some description for your code?
As I didn't notice any changes.
Thank you.

**Comment by ivakub** [comment]
@nightrider77 Sorry, this is a minimized code. We have an issue in [Youtrack](https://youtrack.jetbrains.com/issue/KT-38747).

**Comment by PetukhovVictor** [comment]
FYI: it has been fixed, and is going to be available since Kotlin 1.5.0-RC.

**Comment by akurasov** [comment]
Not reproducible on:
IDEA 2021.2(Ultimate edition) + kotlin 1.5.10-IJ4746.92
and
AS Arctic Fox 2020.3.1+kotlin 1.5.21-release-316

Does someone still have this issue?

**Comment by akurasov** [comment]
Seems to be fixed

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6309">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
