### ISSUE TITLE
Questions about TextField Chinese input

### ISSUE THREAD

**Issue by nukiyoam** [JetBrains/compose-jb#672]
I had some problems trying to use Chinese input in the TextField component.

When the program is just started, it is possible to type Chinese in TextField normally. However, if you delete the previous text after typing Chinese, and then type it again, the text will overwrite the previous text.

Another problem is that if you empty the entire TextField, you will not be able to type Chinese again and you will get the following error:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: start cannot be negative. [start: -1]
	at androidx.compose.ui.text.TextRangeKt.packWithCheck(TextRange.kt:121)
	at androidx.compose.ui.text.TextRangeKt.TextRange(TextRange.kt:37)
	at androidx.compose.ui.text.input.EditingBuffer.delete$ui_text(EditingBuffer.kt:190)
	at androidx.compose.ui.text.input.DeleteSurroundingTextInCodePointsCommand.applyTo(EditCommand.kt:354)
	at androidx.compose.ui.text.input.EditProcessor.apply(EditProcessor.kt:93)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.onEditCommand(TextFieldDelegate.kt:202)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion.access$onEditCommand(TextFieldDelegate.kt:90)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:250)
	at androidx.compose.foundation.text.TextFieldDelegate$Companion$restartInput$1.invoke(TextFieldDelegate.kt:250)
	at androidx.compose.ui.platform.DesktopPlatformInput.replaceInputMethodText$ui(DesktopPlatformInput.desktop.kt:135)
	at androidx.compose.ui.platform.DesktopOwners.onInputMethodEvent(DesktopOwners.desktop.kt:183)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:142)
	at androidx.compose.desktop.ComposeLayer$initCanvas$1$inputMethodTextChanged$1.invoke(ComposeLayer.desktop.kt:141)
	at androidx.compose.desktop.AWTDebounceEventQueue$job$1.invokeSuspend(AWTDebounceEventQueue.desktop.kt:57)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

https://user-images.githubusercontent.com/19466118/118457372-45a7c900-b72c-11eb-856e-b05c8ca09f34.mov

ComposeVesion: 0.4.0-build190
JDK: Oracle jdk15
OS: mac bigsur 11.4
SkikoVersion: 0.2.33 (If you use the skiko version that compose-jb depends on, you can’t enter Chinese, so I rely on the latest version of skiko myself.  see   [The TextField component cannot be typed in Chinese](https://github.com/JetBrains/compose-jb/issues/655) )

**Comment by prepor** [comment]
relates to https://github.com/JetBrains/compose-jb/issues/1070 and should be fixed by https://android-review.googlesource.com/c/platform/frameworks/support/+/1798088

**Comment by nukiyoam** [comment]
> relates to #1070 and should be fixed by https://android-review.googlesource.com/c/platform/frameworks/support/+/1798088

This change fixes the error in the program, but when you delete a character in TextField and then type Chinese again, the problem remains that the last character of the original TextField text will be replaced, as shown in the video above.

I think it should be caused by the code logic here.

[https://github.com/androidx/androidx/blob/f468d9b8445caee945ae8883e58816d2c738cc79/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/DesktopPlatformInput.desktop.kt#L124](https://github.com/androidx/androidx/blob/f468d9b8445caee945ae8883e58816d2c738cc79/compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/platform/DesktopPlatformInput.desktop.kt#L124)

Please forgive my poor English

**Comment by nukiyoam** [comment]
fixed in version 1.1.0 👍，close it

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5416">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
